#+OPTIONS: title:t date:t author:t email:t
#+OPTIONS: toc:t h:6 num:nil |:t todo:nil
#+OPTIONS: *:t -:t ::t <:t \n:t e:t creator:nil
#+OPTIONS: f:t inline:t tasks:t tex:t timestamp:t
#+OPTIONS: html-preamble:t html-postamble:nil

#+TITLE:   Arch Linux
#+DATE:	   {{{time(%B %d\, %Y)}}}
#+AUTHOR:  Marie-Hélène Burle
#+EMAIL:   msb2@sfu.ca

Presenting Arch Linux:

Is your Operating System Windows, macOS, or a prepackaged linux distribution running "out-of-the box" like Ubuntu and are you curious to hear about Arch Linux?

I will introduce this linux distribution which [["focuses on elegance, code correctness, minimalism and simplicity, and expects the user to be willing to make some effort to understand the system's operation"][https://en.wikipedia.org/wiki/Arch_Linux]]. It relies on the [[KISS principle][https://en.wikipedia.org/wiki/KISS_principle]] ("keep it simple, stupid"): no bloatware, nothing installed that you might not want, no hidden complexity. Arch has a beautiful [[Wiki][https://wiki.archlinux.org/]], so well done that it serves as a reference for many on other linux distributions, and a very helpful community. Obviously, the necessary consequence of its philosophy is that it requires some investment as you will have to set and install everything you need.

If you have always been curious—or maybe even tempted—to make a big jump and go linux, this workshop is for you!

I will present the basic functioning of this OS and some of the tools that can make a workflow on linux really fun.

The workshop is open to all and those interested in playing with Arch are welcome to install it using VirtualBox (this is not necessary and you are welcome to just sit and watch).
